# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: db28459cf0fe28e4f0bc90b9d0a8e0f7329f8095ebcfd5cd5c72bdd395be85e33de04688451ca61f6d09336cc03940785cf9795246ffaadf86a97a7e1c3ef327

test:
  secret_key_base: 237af96eb824e5eecfa6b57a87a134404973a8bc3fbf52e4818e2d7962ffb8d5b2b1ff8b62ca0ac38e95c3c3f3bcf0a92645b601a1415917b3c034a5bf7f178d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
